### ISSUE TITLE
Missing dependencies

### ISSUE THREAD

**Issue by edufschmidt** [rafaelmendes/bci_training_platform#5]
The modules pyserial and biosig are missing in the install instructions

**Comment by arellanon** [comment]
Hi!  I am trying to run the project without success.

I am trying to install Biosig for python3 but I have the following error:

```
nahuel@nahuel-Notebook:~/Documents/biosig-2.0.6$ python3 -c "import biosig"
Segmentation fault (core dumped)
```

I have Linux Mint 19 Tara and Python 3.7.5

When i run the project:

```
nahuel@nahuel-Notebook:~/Documents/bcitp$ python main.py 
[INFO   ] [Logger      ] Record log in /home/nahuel/.kivy/logs/kivy_20-10-04_9.txt
[INFO   ] [Kivy        ] v1.11.1
[INFO   ] [Kivy        ] Installed at "/home/nahuel/.local/lib/python3.7/site-packages/kivy/__init__.py"
[INFO   ] [Python      ] v3.7.5 (default, Nov  7 2019, 10:50:52) 
[GCC 8.3.0]
[INFO   ] [Python      ] Interpreter at "/usr/bin/python3"
[INFO   ] [Factory     ] 184 symbols loaded
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_sdl2, img_pil, img_gif (img_ffpyplayer ignored)
[INFO   ] [Text        ] Provider: sdl2
 Traceback (most recent call last):
   File "main.py", line 21, in <module>
     from bcitp.screens.ml.ml_screen import MlMenu
   File "/home/nahuel/Documents/TESIS/bcitp/bcitp/screens/ml/ml_screen.py", line 6, in <module>
     from bcitp.signal_processing.approach import Approach
   File "/home/nahuel/Documents/TESIS/bcitp/bcitp/signal_processing/approach.py", line 2, in <module>
     from .utils import nanCleaner
   File "/home/nahuel/Documents/TESIS/bcitp/bcitp/signal_processing/utils.py", line 19, in <module>
     import biosig
 ImportError: /usr/lib/libbiosig.so.1: undefined symbol: cholmod_print_sparse


```

**Comment by arellanon** [comment]
Hello! I am trying to run the calibration from BCItp but I get the following error:

 Traceback (most recent call last):
   File "/home/nahuel/anaconda3/lib/python3.7/threading.py", line 926, in _bootstrap_inner
     self.run()
   File "/home/nahuel/Documents/bcitp/bcitp/utils/sample_manager.py", line 116, in run
     self.board.start_streaming(self.GetData)
   File "/home/nahuel/Documents/bcitp/bcitp/hardware/open_bci_v3.py", line 194, in start_streaming
     call(sample)
   File "/home/nahuel/Documents/bcitp/bcitp/utils/sample_manager.py", line 155, in GetData
     if self.sample_counter > self.playbackData.shape[0] - 30:
 AttributeError: 'SampleManager' object has no attribute 'playbackData'
